Creating collection view
ann-oksa/newsfeed pull request #4
Opened 2021-02-22 18:01 UTC by ann-oksa

Worked on creating collection view and custom cell
Collection view shows 20 different news with image, title, content of article ect.
Created base for layout and next changing with it.
Have some issue with "for in" loop and creating array of models depends on news count, will be thankful for an advice

2021-02-22 19:45 UTC, dement0rs requested changes

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/Models/Identifiers.swift
> +    let identifierForCell = "cellForNews"
1. Обычно reuseIdentifier для ячейки таблицы или collectionView называют так же, как соответствующий класс, то есть, "CollectionViewCell"
2. переменную лучше связать с CollectionViewCell, так как она только к нему имеет отношение, например
class CollectionViewCell {
   static let reuseIdentifier = "CollectionViewCell"
}

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/NetworkFiles/EverythingRequest.swift
> +  //  let page = 1
page же тоже параметр запроса, почему он убран?

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/NetworkFiles/GoogleNewsAPI.swift
> +                        completionHandler(.failure(ErrorsFormatForHTTPSRequest(status: "Error", code: String( response.statusCode) , message: "There is no data from this URL")))
здесь лучше создание объекта error лучше вынести в отдельную строчку, а то слишком длинно

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/NetworkFiles/GoogleNewsAPI.swift
> +                        completionHandler(.failure(ErrorsFormatForHTTPSRequest(status: "Error", code: String( response.statusCode), message: error.localizedDescription)))
здесь тоже

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/NewsFeed/NewsFeedViewController.swift
> +    let identifier = Identifiers()
про reuseIdentifier выше писал

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/NewsFeed/NewsFeedViewController.swift
> +        let  nib = UINib(nibName: "CollectionViewCell", bundle: nil)
nib name для CollectionViewCell можно сделать статической переменной по аналогии с reuseIdentifier

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/ViewModels/NewsViewModel.swift
> +protocol NewsViewModelDelegateProtocol: class {
слово Protocol в имени избыточно, кажется, без него, смысл сохранится

2021-02-22 19:45 UTC, dement0rs commented on newsfeed/ViewModels/NewsViewModel.swift
> +                    if result.totalResults > self.everything.pageSize {
```
var index: Int = 0
for article in response.articles {
   let modelForNewsCell = ModelForNewsCell(article: article)
   modelsForNewsCell.append(modelForNewsCell)
   index + =1
   if index > self.everything.pageSize - 1 {
      break
   }
}
```

возможно, где-то напутал с индексами, но идея такая

2021-02-23 09:02 UTC, ann-oksa commented on newsfeed/Models/Identifiers.swift
> +    let identifierForCell = "cellForNews"
создать можно, но невозможно использовать такую переменную   
static let reuseIdentifier = "CollectionViewCell"
в классе NewsFeedViewController я создаю экземпляр класса CollectionViewCell, но он не видит ее свойства
возможно стоит создать эту константу сразу в классе  NewsFeedViewController?

2021-02-23 09:39 UTC, dement0rs commented on newsfeed/Models/Identifiers.swift
> +    let identifierForCell = "cellForNews"
static  - это переменная класса. Обращаться к ней нужно не через экземпляры класса, а через сам класс
CollectionViewCell.reuseIdentifier

2021-02-23 12:11 UTC, dement0rs approved these changes
Я оставил еще мелкие комменты, но в целом - good to go

2021-02-23 12:11 UTC, dement0rs commented on newsfeed/CellForNews/CollectionViewCell.swift
> +        // Initialization code
давай вырабатывать привычку удалять подобные закомментированые куски и пробелы

2021-02-23 12:11 UTC, dement0rs commented on newsfeed/NetworkFiles/GoogleNewsAPI.swift
> +            completionHandler(.failure(
```
let error = ErrorsFormatForHTTPSRequest(status: "Error", code: "Status code ", message: "Can`t create URL with input endpoint and QueryItems"))
```
скорее так. Разница в том, что вызов completionHandler-a и создание ошибки в разных отделены

2021-02-23 12:11 UTC, dement0rs commented on newsfeed/NetworkFiles/GoogleNewsAPI.swift
> +                    completionHandler(.failure(
см выше

2021-02-23 12:11 UTC, dement0rs commented on newsfeed/ViewModels/ModelForNewsCell.swift
> +        self.imageString = article.urlToImage ?? "Some string"
имеет смысл переименовать imageString в imageURL?

2021-02-24 07:18 UTC, merged